from __future__ import annotations

import json
from pathlib import Path

from scripts import architecture_report


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def test_architecture_report_collects_large_files_and_import_boundary_issues(
    tmp_path: Path,
) -> None:
    _write(tmp_path / "src/focus_agent/service.py", "import scripts.release_gate\n")
    _write(tmp_path / "scripts/tool.py", "print('ok')\n")
    _write(tmp_path / "apps/web/src/view.ts", "import x from 'src/focus_agent/api'\n")
    _write(tmp_path / "frontend-sdk/src/client.ts", "\n".join(["export const x = 1;"] * 6))

    report = architecture_report.build_architecture_report(
        root=tmp_path,
        scan_paths=["src/focus_agent", "scripts", "apps/web/src", "frontend-sdk/src"],
        large_file_threshold=5,
    )

    assert report["summary"]["blocking"] is False
    assert report["summary"]["status"] == "issues"
    assert report["line_count_top10"][0] == {
        "lines": 6,
        "path": "frontend-sdk/src/client.ts",
    }
    assert {item["path"] for item in report["large_files"]} == {"frontend-sdk/src/client.ts"}
    assert report["summary"]["near_large_file_count"] == 0
    assert {item["path"] for item in report["import_boundary_issues"]} == {
        "apps/web/src/view.ts",
        "src/focus_agent/service.py",
    }


def test_architecture_report_cli_is_non_blocking(tmp_path: Path, capsys) -> None:
    _write(tmp_path / "src/focus_agent/large.py", "\n".join(["x = 1"] * 4))
    report_json = tmp_path / "report.json"

    exit_code = architecture_report.main(
        [
            "--root",
            str(tmp_path),
            "--path",
            "src/focus_agent",
            "--large-file-threshold",
            "1",
            "--report-json",
            str(report_json),
        ]
    )

    stdout = json.loads(capsys.readouterr().out)
    saved = json.loads(report_json.read_text(encoding="utf-8"))
    assert exit_code == 0
    assert stdout["blocking"] is False
    assert stdout["issue_count"] == 1
    assert stdout["line_count_top10"] == [{"lines": 4, "path": "src/focus_agent/large.py"}]
    assert stdout["near_large_file_count"] == 0
    assert saved["summary"]["status"] == "issues"
    assert saved["line_count_top10"] == stdout["line_count_top10"]


def test_architecture_report_ignores_generated_files_for_maintenance_size(
    tmp_path: Path,
) -> None:
    _write(
        tmp_path / "frontend-sdk/src/types/__generated__.ts",
        "\n".join(
            [
                "/**",
                " * This file was auto-generated by openapi-typescript.",
                " * Do not make direct changes to the file.",
                " */",
                "export const generated = 1;",
                "export const generated2 = 2;",
            ]
        ),
    )
    _write(tmp_path / "frontend-sdk/src/client.ts", "\n".join(["export const x = 1;"] * 4))

    report = architecture_report.build_architecture_report(
        root=tmp_path,
        scan_paths=["frontend-sdk/src"],
        large_file_threshold=5,
    )

    assert report["summary"]["large_file_count"] == 0
    assert report["line_count_top10"] == [{"lines": 4, "path": "frontend-sdk/src/client.ts"}]


def test_architecture_report_does_not_trust_generated_marker_in_arbitrary_file(
    tmp_path: Path,
) -> None:
    _write(
        tmp_path / "src/focus_agent/hidden.py",
        "\n".join(
            [
                "# This file was auto-generated",
                "# Do not make direct changes",
                "x = 1",
                "x = 2",
            ]
        ),
    )

    report = architecture_report.build_architecture_report(
        root=tmp_path,
        scan_paths=["src/focus_agent"],
        large_file_threshold=2,
    )

    assert report["summary"]["large_file_count"] == 1
    assert report["large_files"][0]["path"] == "src/focus_agent/hidden.py"


def test_architecture_report_surfaces_near_threshold_files_without_issue(
    tmp_path: Path,
) -> None:
    _write(tmp_path / "src/focus_agent/almost_large.py", "\n".join(["x = 1"] * 4))
    _write(tmp_path / "src/focus_agent/small.py", "\n".join(["x = 1"] * 2))

    report = architecture_report.build_architecture_report(
        root=tmp_path,
        scan_paths=["src/focus_agent"],
        large_file_threshold=5,
        large_file_warning_ratio=0.8,
    )

    assert report["summary"]["status"] == "ok"
    assert report["summary"]["issue_count"] == 0
    assert report["summary"]["near_large_file_count"] == 1
    assert report["near_large_files"] == [
        {
            "lines": 4,
            "path": "src/focus_agent/almost_large.py",
            "threshold": 5,
            "warning_at": 4,
        }
    ]


def test_architecture_regression_gate_rejects_new_and_growing_large_files() -> None:
    report = {
        "large_files": [
            {"path": "src/focus_agent/existing.py", "lines": 11},
            {"path": "src/focus_agent/new.py", "lines": 9},
        ],
        "import_boundary_issues": [{"path": "src/focus_agent/service.py"}],
    }
    baseline = {
        "large_files": {
            "src/focus_agent/existing.py": {
                "max_lines": 10,
                "owner": "runtime",
                "exit_criteria": "split responsibilities",
            }
        }
    }

    assert architecture_report.architecture_regressions(report, baseline) == [
        "large file grew: src/focus_agent/existing.py (11 > 10)",
        "new large file: src/focus_agent/new.py (9 lines)",
        "import boundary issues: 1",
    ]


def test_architecture_regression_gate_allows_debt_reduction() -> None:
    report = {
        "large_files": [{"path": "src/focus_agent/existing.py", "lines": 9}],
        "import_boundary_issues": [],
    }
    baseline = {
        "large_files": {
            "src/focus_agent/existing.py": {
                "max_lines": 10,
                "owner": "runtime",
                "exit_criteria": "split responsibilities",
            }
        }
    }

    assert architecture_report.architecture_regressions(report, baseline) == []


def test_architecture_regression_gate_rejects_a_resolved_file_that_becomes_large_again() -> None:
    baseline = architecture_report.load_architecture_baseline(
        architecture_report.DEFAULT_BASELINE_JSON,
        root=architecture_report.REPO_ROOT,
    )
    report = {
        "large_files": [{"path": "src/focus_agent/engine/graph/agent_loop.py", "lines": 801}],
        "import_boundary_issues": [],
    }

    assert baseline["large_file_threshold"] == 800
    assert baseline["large_files"] == {}
    assert architecture_report.architecture_regressions(report, baseline) == [
        "new large file: src/focus_agent/engine/graph/agent_loop.py (801 lines)"
    ]


def test_architecture_regression_gate_rejects_policy_overrides(capsys) -> None:
    override_sets = [
        ["--root", "/tmp"],
        ["--path", "src/focus_agent/engine"],
        ["--large-file-threshold", "999999"],
        ["--baseline-json", "/tmp/empty-baseline.json"],
    ]

    for override in override_sets:
        assert architecture_report.main(["--fail-on-regression", *override]) == 2
        payload = json.loads(capsys.readouterr().out)
        assert payload["blocking"] is True
        assert payload["status"] == "invalid"
        assert override[0] in payload["error"]
