export const queryKeys = {
  principal: ["principal"] as const,
  models: ["models"] as const,
  conversations: ["conversations"] as const,
  thread: (threadId: string) => ["thread", threadId] as const,
  branchTree: (rootThreadId: string) => ["branch-tree", rootThreadId] as const,
  trajectoryList: (filtersKey: string) => ["trajectory-list", filtersKey] as const,
  trajectoryDetail: (turnId: string) => ["trajectory-detail", turnId] as const,
  trajectoryStats: (filtersKey: string) => ["trajectory-stats", filtersKey] as const,
  observabilityOverview: (filtersKey: string) => ["observability-overview", filtersKey] as const,
  agentRolePolicy: ["agent-role-policy"] as const,
  agentRoleDecisions: (limit: number) => ["agent-role-decisions", limit] as const,
  agentCapabilities: ["agent-capabilities"] as const,
  agentToolRouteDecisions: (limit: number) => ["agent-tool-route-decisions", limit] as const,
  agentMemoryCuratorPolicy: ["agent-memory-curator-policy"] as const,
  agentMemoryCuratorDecisions: (limit: number) => ["agent-memory-curator-decisions", limit] as const,
};
