export const queryKeys = {
  principal: ["principal"] as const,
  models: ["models"] as const,
  conversations: ["conversations"] as const,
  thread: (threadId: string) => ["thread", threadId] as const,
  branchTree: (rootThreadId: string) => ["branch-tree", rootThreadId] as const,
  trajectoryList: (filtersKey: string) => ["trajectory-list", filtersKey] as const,
  trajectoryDetail: (turnId: string) => ["trajectory-detail", turnId] as const,
  trajectoryStats: (filtersKey: string) => ["trajectory-stats", filtersKey] as const,
  observabilityOverview: (filtersKey: string) => ["observability-overview", filtersKey] as const,
  agentRolePolicy: ["agent-role-policy"] as const,
  agentRoleDecisions: (limit: number) => ["agent-role-decisions", limit] as const,
  agentCapabilities: ["agent-capabilities"] as const,
  agentToolRouteDecisions: (limit: number) => ["agent-tool-route-decisions", limit] as const,
  agentMemoryCuratorPolicy: ["agent-memory-curator-policy"] as const,
  agentMemoryCuratorDecisions: (limit: number) => ["agent-memory-curator-decisions", limit] as const,
  agentDelegationPolicy: ["agent-delegation-policy"] as const,
  agentDelegationRuns: (limit: number) => ["agent-delegation-runs", limit] as const,
  agentModelRouterPolicy: ["agent-model-router-policy"] as const,
  agentModelRouterDecisions: (limit: number) => ["agent-model-router-decisions", limit] as const,
  agentSelfRepairFailures: (limit: number) => ["agent-self-repair-failures", limit] as const,
  agentReviewQueue: (limit: number) => ["agent-review-queue", limit] as const,
  agentContextPolicy: ["agent-context-policy"] as const,
  agentContextDecisions: (limit: number) => ["agent-context-decisions", limit] as const,
  agentContextArtifacts: (limit: number) => ["agent-context-artifacts", limit] as const,
  agentTaskLedgerPolicy: ["agent-task-ledger-policy"] as const,
  agentTaskLedgerRuns: (limit: number) => ["agent-task-ledger-runs", limit] as const,
  agentArtifacts: (limit: number) => ["agent-artifacts", limit] as const,
  agentCriticVerdicts: (limit: number) => ["agent-critic-verdicts", limit] as const,
};
