"""Release gate command catalog and production signal bindings."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

DEFAULT_COMMAND_TIMEOUT_S = 30 * 60


@dataclass(frozen=True)
class GateCommand:
    label: str
    command: tuple[str, ...]
    timeout_s: float | None = DEFAULT_COMMAND_TIMEOUT_S


def production_signal_commands() -> list[list[str]]:
    return [
        ["rm", "-rf", "reports/release-gate-raw"],
        ["mkdir", "-p", "reports/release-gate-raw"],
        [
            "rm",
            "-f",
            "reports/release-gate/readyz.json",
            "reports/release-gate/trajectory-stats.json",
            "reports/release-gate/replay-comparisons.json",
            "reports/release-gate/alert-report.json",
            "reports/release-gate/postgres-migration.json",
            "reports/release-gate/baseline-eval-smoke.json",
        ],
        [
            "python",
            "scripts/release_gate.py",
            "deployment-binding",
            "--output",
            "${DEPLOYMENT_BINDING_JSON}",
        ],
        [
            "curl",
            "--fail",
            "--show-error",
            "--silent",
            "--output",
            "reports/release-gate-raw/readyz.json",
            "--",
            "$READY_URL",
        ],
        [
            "uv",
            "run",
            "python",
            "scripts/release_evidence_capture.py",
            "reports/release-gate-raw/readyz.json",
            "--output",
            "reports/release-gate/readyz.json",
            "--readyz",
            "reports/release-gate-raw/readyz.json",
            "--captured-now",
        ],
        [
            "curl",
            "--fail",
            "--show-error",
            "--silent",
            "--output",
            "reports/release-gate-raw/trajectory-stats.json",
            "--",
            "$TRAJECTORY_STATS_URL",
        ],
        [
            "uv",
            "run",
            "python",
            "scripts/release_evidence_capture.py",
            "reports/release-gate-raw/trajectory-stats.json",
            "--output",
            "reports/release-gate/trajectory-stats.json",
            "--captured-now",
        ],
        [
            "curl",
            "--fail",
            "--show-error",
            "--silent",
            "--output",
            "reports/release-gate-raw/replay-comparisons.json",
            "--",
            "$REPLAY_COMPARISONS_URL",
        ],
        [
            "uv",
            "run",
            "python",
            "scripts/release_evidence_capture.py",
            "reports/release-gate-raw/replay-comparisons.json",
            "--output",
            "reports/release-gate/replay-comparisons.json",
        ],
        [
            "curl",
            "--fail",
            "--show-error",
            "--silent",
            "--output",
            "reports/release-gate-raw/alert-report.json",
            "--",
            "$ALERT_REPORT_URL",
        ],
        [
            "uv",
            "run",
            "python",
            "scripts/release_evidence_capture.py",
            "reports/release-gate-raw/alert-report.json",
            "--output",
            "reports/release-gate/alert-report.json",
        ],
        [
            "curl",
            "--fail",
            "--show-error",
            "--silent",
            "--output",
            "reports/release-gate-raw/postgres-migration.json",
            "--",
            "$POSTGRES_MIGRATION_REPORT_URL",
        ],
        [
            "uv",
            "run",
            "python",
            "scripts/release_evidence_capture.py",
            "reports/release-gate-raw/postgres-migration.json",
            "--output",
            "reports/release-gate/postgres-migration.json",
        ],
        [
            "curl",
            "--fail",
            "--show-error",
            "--silent",
            "--output",
            "reports/release-gate-raw/baseline-eval-smoke.json",
            "--",
            "$BASELINE_EVAL_REPORT_URL",
        ],
        [
            "uv",
            "run",
            "python",
            "scripts/release_evidence_capture.py",
            "reports/release-gate-raw/baseline-eval-smoke.json",
            "--output",
            "reports/release-gate/baseline-eval-smoke.json",
        ],
        ["rm", "-rf", "reports/release-gate-raw"],
        [
            "uv",
            "run",
            "python",
            "scripts/production_smoke.py",
            "--report-json",
            "reports/release-gate/production-smoke.json",
        ],
        [
            "uv",
            "run",
            "python",
            "scripts/postgres_ops.py",
            "--report-json",
            "reports/release-gate/postgres-ops.json",
        ],
        [
            "uv",
            "run",
            "python",
            "scripts/otel_smoke.py",
            "--endpoint",
            "$OTEL_ENDPOINT",
            "--collector-health-url",
            "$OTEL_COLLECTOR_HEALTH_URL",
            "--trace-query-url",
            "$OTEL_TRACE_QUERY_URL",
            "--report-json",
            "reports/release-gate/otel-smoke.json",
        ],
        ["test", "-s", "$GOVERNANCE_REPORT_JSON"],
    ]


def production_release_evidence_args() -> list[str]:
    return [
        "--release-id",
        "${RELEASE_ID}",
        "--commit-sha",
        "${RELEASE_COMMIT_SHA}",
        "--deployment-id",
        "${RELEASE_DEPLOYMENT_ID}",
        "--deployment-version",
        "${RELEASE_DEPLOYMENT_VERSION}",
        "--environment",
        "${RELEASE_ENVIRONMENT}",
        "--approval-id",
        "${APPROVAL_ID}",
        "--approval-status",
        "${APPROVAL_STATUS}",
        "--approval-url",
        "${APPROVAL_URL}",
        "--retention-days",
        "${RETENTION_DAYS}",
        "--storage-dir",
        "${ARTIFACT_STORAGE_DIR}",
        "--readyz-json",
        "reports/release-gate/readyz.json",
        "--trajectory-stats-json",
        "reports/release-gate/trajectory-stats.json",
        "--replay-comparisons-json",
        "reports/release-gate/replay-comparisons.json",
        "--alert-report-json",
        "reports/release-gate/alert-report.json",
        "--postgres-migration-report-json",
        "reports/release-gate/postgres-migration.json",
        "--production-smoke-report-json",
        "reports/release-gate/production-smoke.json",
        "--postgres-ops-report-json",
        "reports/release-gate/postgres-ops.json",
        "--otel-smoke-report-json",
        "reports/release-gate/otel-smoke.json",
        "--governance-report-json",
        "${GOVERNANCE_REPORT_JSON}",
        "--eval-report-json",
        "reports/release-gate/eval-smoke.json",
        "--eval-report-json",
        "reports/release-gate/eval-observability.json",
        "--eval-report-json",
        "reports/release-gate/eval-golden-multi-agent.json",
        "--eval-report-json",
        "reports/release-gate/eval-harness-stability.json",
        "--eval-report-json",
        "reports/release-gate/memory-context-eval.json",
        "--baseline-eval-report-json",
        "reports/release-gate/baseline-eval-smoke.json",
    ]


PRODUCTION_SIGNAL_MAPPINGS: tuple[dict[str, Any], ...] = (
    {
        "key": "release_commit_sha",
        "env": "RELEASE_COMMIT_SHA",
        "source": "github.sha",
        "used_by": "release_evidence_capture attestation and release-evidence --commit-sha",
    },
    {
        "key": "release_deployment_id",
        "env": "RELEASE_DEPLOYMENT_ID",
        "source": "vars.FOCUS_AGENT_DEPLOYMENT_ID",
        "used_by": "release_evidence_capture attestation/readyz validation and release-evidence --deployment-id",
    },
    {
        "key": "release_deployment_version",
        "env": "RELEASE_DEPLOYMENT_VERSION",
        "source": "vars.FOCUS_AGENT_DEPLOYMENT_VERSION",
        "used_by": "release_evidence_capture attestation/readyz validation and release-evidence --deployment-version",
    },
    {
        "key": "release_environment",
        "env": "RELEASE_ENVIRONMENT",
        "source": "hardcoded production job environment",
        "used_by": "release_evidence_capture attestation/readyz validation and release-evidence --environment",
    },
    {
        "key": "base_url",
        "env": "BASE_URL",
        "source": "vars.FOCUS_AGENT_BASE_URL",
        "used_by": "production-smoke --base-url/--web-base-url",
    },
    {
        "key": "readyz",
        "env": "READY_URL",
        "source": "vars.FOCUS_AGENT_READY_URL",
        "artifact_path": "reports/release-gate/readyz.json",
        "used_by": "release_evidence_capture --captured-now/--readyz, then release-evidence --readyz-json",
    },
    {
        "key": "trajectory_stats",
        "env": "TRAJECTORY_STATS_URL",
        "source": "vars.FOCUS_AGENT_TRAJECTORY_STATS_URL",
        "artifact_path": "reports/release-gate/trajectory-stats.json",
        "used_by": "release_evidence_capture --captured-now, then release-evidence --trajectory-stats-json",
    },
    {
        "key": "replay_comparison",
        "env": "REPLAY_COMPARISONS_URL",
        "source": "vars.FOCUS_AGENT_REPLAY_COMPARISONS_URL",
        "artifact_path": "reports/release-gate/replay-comparisons.json",
        "used_by": "release_evidence_capture with required upstream timestamp, then release-evidence --replay-comparisons-json",
    },
    {
        "key": "alert_report",
        "env": "ALERT_REPORT_URL",
        "source": "vars.FOCUS_AGENT_ALERT_REPORT_URL",
        "artifact_path": "reports/release-gate/alert-report.json",
        "used_by": "release_evidence_capture with required upstream timestamp, then release-evidence --alert-report-json",
    },
    {
        "key": "postgres_migration_report",
        "env": "POSTGRES_MIGRATION_REPORT_URL",
        "source": "vars.FOCUS_AGENT_POSTGRES_MIGRATION_REPORT_URL",
        "artifact_path": "reports/release-gate/postgres-migration.json",
        "used_by": "release_evidence_capture with required upstream timestamp, then release-evidence --postgres-migration-report-json",
    },
    {
        "key": "baseline_eval",
        "env": "BASELINE_EVAL_REPORT_URL",
        "source": "vars.FOCUS_AGENT_BASELINE_EVAL_REPORT_URL",
        "artifact_path": "reports/release-gate/baseline-eval-smoke.json",
        "used_by": "release_evidence_capture with required upstream timestamp, then release-evidence --baseline-eval-report-json",
    },
    {
        "key": "approval_id",
        "env": "APPROVAL_ID",
        "source": "workflow_dispatch.inputs.approval_id",
        "used_by": "release-evidence --approval-id",
    },
    {
        "key": "approval_status",
        "env": "APPROVAL_STATUS",
        "source": "workflow_dispatch.inputs.approval_status",
        "used_by": "release-evidence --approval-status",
    },
    {
        "key": "approval_url",
        "env": "APPROVAL_URL",
        "source": "workflow_dispatch.inputs.approval_url or github workflow run URL",
        "used_by": "release-evidence --approval-url",
    },
    {
        "key": "artifact_storage",
        "env": "ARTIFACT_STORAGE_DIR",
        "source": "job.env.ARTIFACT_STORAGE_DIR",
        "used_by": "release-evidence --storage-dir",
    },
    {
        "key": "artifact_retention",
        "env": "RETENTION_DAYS",
        "source": "workflow_dispatch.inputs.retention_days",
        "used_by": "release-evidence --retention-days and actions/upload-artifact retention-days",
    },
    {
        "key": "environment_name",
        "env": "ENVIRONMENT_NAME",
        "source": "workflow_dispatch.inputs.environment_name or release-dry-run",
        "used_by": "GitHub protected Environment and release evidence ci metadata",
    },
    {
        "key": "smoke_auth_token",
        "env": "AUTH_TOKEN",
        "source": "secrets.FOCUS_AGENT_SMOKE_AUTH_TOKEN or vars.FOCUS_AGENT_SMOKE_AUTH_TOKEN",
        "used_by": "production-smoke --auth-token",
    },
    {
        "key": "stream_events_report_url",
        "env": "STREAM_EVENTS_REPORT_URL",
        "required_in_production": False,
        "source": "vars.FOCUS_AGENT_STREAM_EVENTS_REPORT_URL",
        "artifact_path": "reports/release-gate/stream-events.json",
        "used_by": "workflow release_evidence_capture with required upstream timestamp, then production-smoke --stream-events-json",
    },
    {
        "key": "stream_events_url",
        "env": "STREAM_EVENTS_URL",
        "required_in_production": False,
        "source": "vars.FOCUS_AGENT_STREAM_EVENTS_URL",
        "used_by": "production-smoke --stream-events-url",
    },
    {
        "key": "database_uri",
        "env": "DATABASE_URI",
        "source": "secrets.FOCUS_AGENT_DATABASE_URI or vars.FOCUS_AGENT_DATABASE_URI",
        "used_by": "postgres-ops --database-uri",
    },
    {
        "key": "postgres_backup_command",
        "env": "POSTGRES_BACKUP_COMMAND",
        "source": "secrets.FOCUS_AGENT_POSTGRES_BACKUP_COMMAND or vars.FOCUS_AGENT_POSTGRES_BACKUP_COMMAND",
        "used_by": "postgres-ops --backup-command",
    },
    {
        "key": "postgres_restore_command",
        "env": "POSTGRES_RESTORE_COMMAND",
        "source": "secrets.FOCUS_AGENT_POSTGRES_RESTORE_COMMAND or vars.FOCUS_AGENT_POSTGRES_RESTORE_COMMAND",
        "used_by": "postgres-ops --restore-command",
    },
    {
        "key": "postgres_restore_verification_query",
        "env": "POSTGRES_RESTORE_VERIFICATION_QUERY",
        "source": "secrets.FOCUS_AGENT_POSTGRES_RESTORE_VERIFICATION_QUERY or vars.FOCUS_AGENT_POSTGRES_RESTORE_VERIFICATION_QUERY",
        "used_by": "postgres-ops --restore-verification-query",
    },
    {
        "key": "postgres_retention_cleanup_query",
        "env": "POSTGRES_RETENTION_CLEANUP_QUERY",
        "source": "secrets.FOCUS_AGENT_POSTGRES_RETENTION_CLEANUP_QUERY or vars.FOCUS_AGENT_POSTGRES_RETENTION_CLEANUP_QUERY",
        "used_by": "postgres-ops --retention-cleanup-query",
    },
    {
        "key": "otel_endpoint",
        "env": "OTEL_ENDPOINT",
        "source": "vars.FOCUS_AGENT_OTEL_ENDPOINT",
        "used_by": "otel-smoke --endpoint",
    },
    {
        "key": "otel_collector_health",
        "env": "OTEL_COLLECTOR_HEALTH_URL",
        "source": "vars.FOCUS_AGENT_OTEL_COLLECTOR_HEALTH_URL",
        "used_by": "otel-smoke --collector-health-url",
    },
    {
        "key": "otel_trace_query",
        "env": "OTEL_TRACE_QUERY_URL",
        "source": "vars.FOCUS_AGENT_OTEL_TRACE_QUERY_URL",
        "used_by": "otel-smoke --trace-query-url",
    },
    {
        "key": "governance_report",
        "env": "GOVERNANCE_REPORT_JSON",
        "source": "job.env.GOVERNANCE_REPORT_JSON",
        "used_by": "release-evidence --governance-report-json",
    },
)


RELEASE_GATE_COMMANDS: tuple[GateCommand, ...] = (
    GateCommand("lint", ("make", "lint")),
    GateCommand("ci-test", ("make", "ci-test")),
    GateCommand("sdk-check", ("make", "sdk-check")),
    GateCommand("sdk-build", ("make", "sdk-build")),
    GateCommand("web-check", ("make", "web-check")),
    GateCommand("web-build", ("make", "web-build")),
    GateCommand(
        "observability-ui-smoke",
        ("uv", "run", "python", "scripts/observability_ui_smoke.py", "--scenario", "all"),
    ),
    GateCommand("web-observability-smoke", ("pnpm", "--dir", "apps/web", "smoke:observability")),
    GateCommand("ui-smoke", ("uv", "run", "python", "scripts/ui_smoke_test.py")),
    GateCommand(
        "eval-smoke",
        (
            "uv",
            "run",
            "python",
            "-m",
            "tests.eval",
            "--suite",
            "smoke",
            "--concurrency",
            "1",
            "--report-json",
            "reports/release-gate/eval-smoke.json",
        ),
    ),
    GateCommand(
        "eval-observability",
        (
            "uv",
            "run",
            "python",
            "-m",
            "tests.eval",
            "--suite",
            "observability",
            "--concurrency",
            "1",
            "--report-json",
            "reports/release-gate/eval-observability.json",
        ),
    ),
    GateCommand(
        "eval-golden-multi-agent",
        (
            "uv",
            "run",
            "python",
            "-m",
            "tests.eval",
            "--suite",
            "golden_multi_agent",
            "--concurrency",
            "1",
            "--report-json",
            "reports/release-gate/eval-golden-multi-agent.json",
        ),
    ),
    GateCommand(
        "eval-harness-stability",
        (
            "uv",
            "run",
            "python",
            "-m",
            "tests.eval",
            "--suite",
            "harness_stability",
            "--concurrency",
            "1",
            "--report-json",
            "reports/release-gate/eval-harness-stability.json",
        ),
    ),
    GateCommand(
        "memory-context-eval",
        (
            "uv",
            "run",
            "python",
            "scripts/memory_context_eval.py",
            "--report-json",
            "reports/release-gate/memory-context-eval.json",
        ),
    ),
    GateCommand(
        "agent-governance-report",
        (
            "uv",
            "run",
            "python",
            "scripts/agent_governance_report.py",
            "--report-json",
            "reports/agent-governance/latest.json",
        ),
    ),
    GateCommand(
        "release-health",
        (
            "uv",
            "run",
            "python",
            "scripts/release_health_check.py",
            "--mode",
            "local",
            "--ready-url",
            "http://127.0.0.1:8000/readyz",
            "--trajectory-stats-url",
            "http://127.0.0.1:8000/v1/observability/trajectory/stats",
            "--allow-self-check-fallback",
            "--eval-report-json",
            "reports/release-gate/eval-smoke.json",
            "--eval-report-json",
            "reports/release-gate/eval-observability.json",
            "--eval-report-json",
            "reports/release-gate/eval-golden-multi-agent.json",
            "--eval-report-json",
            "reports/release-gate/eval-harness-stability.json",
            "--eval-report-json",
            "reports/release-gate/memory-context-eval.json",
            "--governance-report-json",
            "reports/agent-governance/latest.json",
            "--report-json",
            "reports/release-gate/release-health.json",
        ),
    ),
)
